### PR TITLE
fix link to MyRack portal

### PR DESCRIPTION
**Pull request by stephamon**
link to MyRack portal was broken

### CODE REVIEW

**Review by cyrichardson — APPROVED** [review]
LGTM! Thanks, @stephamon!

**Comment by cyrichardson** [comment]
But @stephamon Strider is doing the weird error thing... just needs another bump to run, I think.

**Comment by stephamon** [comment]
Hey @cyrichardson looks like it finally passed! Will you give it a merge for me?

**Comment by cyrichardson** [comment]
@stephamon No build preview. Strider says: Fetch refs/pull/43/merge failed with code 128

I'll do a bump on your branch and see if we get a preview build.

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-b2ece5cd84/docs/dedicated-load-balancers/v2/)

**Comment by cyrichardson** [comment]
@stephamon There you go! Merging now.

**Pull request merged**
