### PR TITLE
remove release notes

### PR DESCRIPTION
**Pull request by catlook**
resolves issue #44 by removing release notes section from repo (it was already removed from the index).

If in the future, the team wants to track release changes, they can add the appropriate pages and directories and the ref in the main index.rst.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-7b4b56f3d4/docs/dedicated-load-balancers/v2/)

**Comment by scotchneat** [comment]
@catlook you think you could also remove the last sentence in [/load-balancer/api-docs/service-updates.rst](https://github.com/rackerlabs/docs-dedicated-networking/blob/master/load-balancer/api-docs/service-updates.rst)? 
It still says `To learn about updates and changes included in this and other releases, see the Release Notes.` Although it no longer links to the Release Notes.

**Comment by catlook** [comment]
Done!

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-ce9db13c31/docs/dedicated-load-balancers/v2/)

**Comment by catlook** [comment]
Many thanks!!

**Pull request merged**
