### PR TITLE
Added note about the service catalog

### PR DESCRIPTION
**Pull request by scotchneat**

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-12d4062b42/docs/dedicated-load-balancers/v2/)

**Review by cyrichardson — APPROVED** [review]
Approved with minor edits

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-4c727ce8b3/docs/dedicated-load-balancers/v2/)

**Comment by scotchneat** [comment]
Got confirmation from DCXOps (they don't have merge access to this).

**Comment by cyrichardson** [comment]
@scotchneat Would you like for me to merge now?

**Comment by scotchneat** [comment]
please @cyrichardson. Thanks!

**Comment by cyrichardson** [comment]
Thanks for your docs contribution, @scotchneat! Merged!

**Pull request merged**
