### PR TITLE
BPI-734 - Updated DNS value to use our public one. Removed ldap roles…

### PR DESCRIPTION
**Pull request by egonzalez777**
… section. Updated request and response section.

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-fb48ae3ca9/docs/dedicated-load-balancers/v2/).

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-cf89b164e5/docs/dedicated-load-balancers/v2/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-7d9826554d/docs/dedicated-load-balancers/v2/).

**Comment by rajeevkct** [comment]
Looks good. merging.

**Pull request merged**
