### PR TITLE
Combined lbs items

### PR DESCRIPTION
**Pull request by egonzalez777**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-4a2f697ab1/docs/dedicated-load-balancers/v2/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-36f4c0b6a0/docs/dedicated-load-balancers/v2/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-32931e6676/docs/dedicated-load-balancers/v2/).

**Comment by rajeevkct** [comment]
Looks Good. Merging.

**Pull request merged**
