### PR TITLE
BPI-818: Remove Early Access Program details

### PR DESCRIPTION
**Pull request by scotchneat**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-dd8a1fd8ba/docs/dedicated-load-balancers/v2/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-4c5a1cad4a/docs/dedicated-load-balancers/v2/).

**Comment by premaseem** [comment]
code Changes looks good.

**Comment by ramanbhati** [comment]
All good here.

**Pull request merged**
