### PR TITLE
BPI-734-v2 - updated docs

### PR DESCRIPTION
**Pull request by rajeevkct**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-74627cf9d8/docs/dedicated-load-balancers/v2/). :bow:

**Review by cyrichardson — COMMENTED** [review]
LGTM! Thanks for your contribution to the docs!

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-fa1b92e90f/docs/dedicated-load-balancers/v2/)

**Review by cyrichardson — APPROVED** [review]
LGTM. Thank you!

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-8a5a40c59e/docs/dedicated-load-balancers/v2/). :bow:

**Review by cyrichardson — APPROVED** [review]
LGTM. Thank you! Let me know if you'd like for me to merge this.

**Pull request merged**
