### PR TITLE
Update docs to match refactored API Guide template

### PR DESCRIPTION
**Pull request by meker12**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-13c2c93675/docs/dedicated-load-balancers/v2/dev-guide/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-286abe1445/docs/dedicated-load-balancers/v2/dev-guide/).

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-6cd0271772/docs/dedicated-load-balancers/v2/dev-guide/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-242d0e6a9d/docs/dedicated-load-balancers/v2/dev-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-7cb88c77bc/docs/dedicated-load-balancers/v2/dev-guide/)

**Comment by meker12** [comment]
@egonzalez777   Check the preview of the refactored API guide.  The change that affects you the most is that I moved the load-balancer-v2.rst file to the `api-reference/methods` folder.

You can merge these updates to your fork, and then update from there.  

Also, when you are ready to update the documentation, let's see if we can parse the methods so the methods can be grouped by resource ((device, virtual IP, node)) instead of being in one huge list like the [Cloud LB API reference](https://developer.rackspace.com/docs/cloud-load-balancers/v1/api-reference/).  See [issue 14](https://github.com/rackerlabs/docs-dedicated-networking/issues/14).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-bf8bf1d2f2/docs/dedicated-load-balancers/v2/dev-guide/). :bow:

**Pull request merged**
